In [1]:
import pandas as pd

In [3]:
import numpy as np

In [55]:
df=pd.read_csv('student.csv')

In [56]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [57]:
df.shape

(10, 5)

In [58]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    10 non-null     int64
 1   name    10 non-null     object
 2   class   10 non-null     object
 3   marks   10 non-null     float64
 4   age     10 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 532.0+ bytes

In [60]:
df.dtypes

roll       int64
name      object
class     object
marks    float64
age        int64
dtype: object

In [61]:
df.head() # Starting 5 values

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [62]:
df.head(7)

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19

In [63]:
df.tail() # It gives from last 5 values

   roll    name class  marks  age
5     6  ayesha    BE  49.55   20
6     7    amar    BE  65.34   19
7     8   amita    BE  68.33   23
8     9    amol    TE  56.75   20
9    10   anmol    BE  78.66   21

In [64]:
df.tail(7)

   roll     name class  marks  age
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [65]:
df.values

array([[1, 'anil', 'TE', 56.77, 22],
       [2, 'amit', 'TE', 59.77, 21],
       [3, 'aniket', 'BE', 76.88, 19],
       [4, 'ajinkya', 'TE', 69.66, 20],
       [5, 'asha', 'TE', 63.28, 20],
       [6, 'ayesha', 'BE', 49.55, 20],
       [7, 'amar', 'BE', 65.34, 19],
       [8, 'amita', 'BE', 68.33, 23],
       [9, 'amol', 'TE', 56.75, 20],
       [10, 'anmol', 'BE', 78.66, 21]], dtype=object)

In [66]:
df.T # Interchange of row into col

,0,1,2,3,4,5,6,7,8,9
roll,1,2,3,4,5,6,7,8,9,10
name,anil,amit,aniket,ajinkya,asha,ayesha,amar,amita,amol,anmol
class,TE,TE,BE,TE,TE,BE,BE,BE,TE,BE
marks,56.77,59.77,76.88,69.66,63.28,49.55,65.34,68.33,56.75,78.66
age,22,21,19,20,20,20,19,23,20,21

In [67]:
# Slicing

In [68]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [69]:
df.iloc[1:4,1:4]

      name class  marks
1     amit    TE  59.77
2   aniket    BE  76.88
3  ajinkya    TE  69.66

In [70]:
df.iloc[0:10,0:6]

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [71]:
df.iloc[1:5,3:5]

   marks  age
1  59.77   21
2  76.88   19
3  69.66   20
4  63.28   20

In [72]:
df.iloc[1:5,[0,1,3]]

   roll     name  marks
1     2     amit  59.77
2     3   aniket  76.88
3     4  ajinkya  69.66
4     5     asha  63.28

In [73]:
df.iloc[6:7,[0,1,3]]

   roll  name  marks
6     7  amar  65.34

In [74]:
df.iloc[[1,2,3,4,6],[0,1,3]]

   roll     name  marks
1     2     amit  59.77
2     3   aniket  76.88
3     4  ajinkya  69.66
4     5     asha  63.28
6     7     amar  65.34

In [75]:
df.iloc[5,1]='geet'

In [76]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6     geet    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [77]:
df.loc[2:5,'name']

2     aniket
3    ajinkya
4       asha
5       geet
Name: name, dtype: object

In [78]:
df.loc[2:5,['name','class']]

      name class
2   aniket    BE
3  ajinkya    TE
4     asha    TE
5     geet    BE

In [90]:
df.loc[:,'name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5       geet
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [81]:
df['name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5       geet
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [83]:
df[['name','class']]

      name class
0     anil    TE
1     amit    TE
2   aniket    BE
3  ajinkya    TE
4     asha    TE
5     geet    BE
6     amar    BE
7    amita    BE
8     amol    TE
9    anmol    BE

In [85]:
#Method on columns/series

In [86]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6     geet    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [87]:
df['name'].str.upper()

0       ANIL
1       AMIT
2     ANIKET
3    AJINKYA
4       ASHA
5       GEET
6       AMAR
7      AMITA
8       AMOL
9      ANMOL
Name: name, dtype: object

In [88]:
df['name'].str.title()

0       Anil
1       Amit
2     Aniket
3    Ajinkya
4       Asha
5       Geet
6       Amar
7      Amita
8       Amol
9      Anmol
Name: name, dtype: object

In [91]:
df['name'].str.lower()

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5       geet
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [94]:
df['name'].str.startswith('a')

0     True
1     True
2     True
3     True
4     True
5    False
6     True
7     True
8     True
9     True
Name: name, dtype: bool

In [95]:
df['name'].str.endswith('l')

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8     True
9     True
Name: name, dtype: bool

In [96]:
df['name'].str.lower()

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5       geet
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [97]:
df['name'].str.title()

0       Anil
1       Amit
2     Aniket
3    Ajinkya
4       Asha
5       Geet
6       Amar
7      Amita
8       Amol
9      Anmol
Name: name, dtype: object

In [108]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6     geet    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [110]:
# Add or Modify the columns

In [111]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6     geet    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [112]:
gender=['m','m','m','f','f','f','f','m','m','f']

In [ ]:
df['gender']=gender

In [117]:
df

   roll     name class  marks  age gender Gender
0     1     anil    TE  56.77   22      m      m
1     2     amit    TE  59.77   21      m      m
2     3   aniket    BE  76.88   19      m      m
3     4  ajinkya    TE  69.66   20      f      f
4     5     asha    TE  63.28   20      f      f
5     6     geet    BE  49.55   20      f      f
6     7     amar    BE  65.34   19      f      f
7     8    amita    BE  68.33   23      m      m
8     9     amol    TE  56.75   20      m      m
9    10    anmol    BE  78.66   21      f      f

In [118]:
df

   roll     name class  marks  age gender Gender
0     1     anil    TE  56.77   22      m      m
1     2     amit    TE  59.77   21      m      m
2     3   aniket    BE  76.88   19      m      m
3     4  ajinkya    TE  69.66   20      f      f
4     5     asha    TE  63.28   20      f      f
5     6     geet    BE  49.55   20      f      f
6     7     amar    BE  65.34   19      f      f
7     8    amita    BE  68.33   23      m      m
8     9     amol    TE  56.75   20      m      m
9    10    anmol    BE  78.66   21      f      f

In [119]:
df['roll']=df['roll']+100

In [120]:
df

   roll     name class  marks  age gender Gender
0   101     anil    TE  56.77   22      m      m
1   102     amit    TE  59.77   21      m      m
2   103   aniket    BE  76.88   19      m      m
3   104  ajinkya    TE  69.66   20      f      f
4   105     asha    TE  63.28   20      f      f
5   106     geet    BE  49.55   20      f      f
6   107     amar    BE  65.34   19      f      f
7   108    amita    BE  68.33   23      m      m
8   109     amol    TE  56.75   20      m      m
9   110    anmol    BE  78.66   21      f      f

In [121]:
# Add a new colunm cgpa
# value should => marks/10+1.5

In [124]:
cgpa=[7.8,9.8,8.8,9.0,6.8,8.9,7.8,8.9,9.9,7.8]

In [125]:
df['CGPA']=cgpa

In [126]:
df

   roll     name class  marks  age gender Gender  CGPA
0   101     anil    TE  56.77   22      m      m   7.8
1   102     amit    TE  59.77   21      m      m   9.8
2   103   aniket    BE  76.88   19      m      m   8.8
3   104  ajinkya    TE  69.66   20      f      f   9.0
4   105     asha    TE  63.28   20      f      f   6.8
5   106     geet    BE  49.55   20      f      f   8.9
6   107     amar    BE  65.34   19      f      f   7.8
7   108    amita    BE  68.33   23      m      m   8.9
8   109     amol    TE  56.75   20      m      m   9.9
9   110    anmol    BE  78.66   21      f      f   7.8

In [127]:
df['CGPA']=df['marks']/10+1.5

In [128]:
df

   roll     name class  marks  age gender Gender   CGPA
0   101     anil    TE  56.77   22      m      m  7.177
1   102     amit    TE  59.77   21      m      m  7.477
2   103   aniket    BE  76.88   19      m      m  9.188
3   104  ajinkya    TE  69.66   20      f      f  8.466
4   105     asha    TE  63.28   20      f      f  7.828
5   106     geet    BE  49.55   20      f      f  6.455
6   107     amar    BE  65.34   19      f      f  8.034
7   108    amita    BE  68.33   23      m      m  8.333
8   109     amol    TE  56.75   20      m      m  7.175
9   110    anmol    BE  78.66   21      f      f  9.366

In [129]:
df.sort_values(by='name')

   roll     name class  marks  age gender Gender   CGPA
3   104  ajinkya    TE  69.66   20      f      f  8.466
6   107     amar    BE  65.34   19      f      f  8.034
1   102     amit    TE  59.77   21      m      m  7.477
7   108    amita    BE  68.33   23      m      m  8.333
8   109     amol    TE  56.75   20      m      m  7.175
2   103   aniket    BE  76.88   19      m      m  9.188
0   101     anil    TE  56.77   22      m      m  7.177
9   110    anmol    BE  78.66   21      f      f  9.366
4   105     asha    TE  63.28   20      f      f  7.828
5   106     geet    BE  49.55   20      f      f  6.455

In [130]:
# Sort by class and then marks simultaneoulsy and check the result

In [133]:
df.sort_values(by=['class','marks'])

   roll     name class  marks  age gender Gender   CGPA
5   106     geet    BE  49.55   20      f      f  6.455
6   107     amar    BE  65.34   19      f      f  8.034
7   108    amita    BE  68.33   23      m      m  8.333
2   103   aniket    BE  76.88   19      m      m  9.188
9   110    anmol    BE  78.66   21      f      f  9.366
8   109     amol    TE  56.75   20      m      m  7.175
0   101     anil    TE  56.77   22      m      m  7.177
1   102     amit    TE  59.77   21      m      m  7.477
4   105     asha    TE  63.28   20      f      f  7.828
3   104  ajinkya    TE  69.66   20      f      f  8.466

In [134]:
df['marks'].max()

78.66

In [136]:
df.describe()

            roll      marks        age       CGPA
count   10.00000  10.000000  10.000000  10.000000
mean   105.50000  64.499000  20.500000   7.949900
std      3.02765   9.207179   1.269296   0.920718
min    101.00000  49.550000  19.000000   6.455000
25%    103.25000  57.520000  20.000000   7.252000
50%    105.50000  64.310000  20.000000   7.931000
75%    107.75000  69.327500  21.000000   8.432750
max    110.00000  78.660000  23.000000   9.366000

In [137]:
df['marks'].mean()

np.float64(64.499)

In [142]:
# GroupBy

In [152]:
gr=df.groupby('class')

gr.groups

In [153]:
12

12

In [154]:
gr.get_group('BE')

   roll    name class  marks  age gender Gender   CGPA
2   103  aniket    BE  76.88   19      m      m  9.188
5   106    geet    BE  49.55   20      f      f  6.455
6   107    amar    BE  65.34   19      f      f  8.034
7   108   amita    BE  68.33   23      m      m  8.333
9   110   anmol    BE  78.66   21      f      f  9.366

In [155]:
gr.min()

       roll     name  marks  age gender Gender   CGPA
class
BE      103     amar  49.55   19      f      f  6.455
TE      101  ajinkya  56.75   20      f      f  7.175

In [156]:
gr['marks'].mean()

class
BE    67.752
TE    61.246
Name: marks, dtype: float64

In [157]:
# boolean filtering

In [158]:
df['marks']>60

0    False
1    False
2     True
3     True
4     True
5    False
6     True
7     True
8    False
9     True
Name: marks, dtype: bool

In [159]:
df[df['marks']>60]

   roll     name class  marks  age gender Gender   CGPA
2   103   aniket    BE  76.88   19      m      m  9.188
3   104  ajinkya    TE  69.66   20      f      f  8.466
4   105     asha    TE  63.28   20      f      f  7.828
6   107     amar    BE  65.34   19      f      f  8.034
7   108    amita    BE  68.33   23      m      m  8.333
9   110    anmol    BE  78.66   21      f      f  9.366

In [160]:
# Filtering data the data of those student->marks>60 and belong to BE class

In [164]:
df[(df['marks']>60) & (df['class']=='BE')]

   roll    name class  marks  age gender Gender   CGPA
2   103  aniket    BE  76.88   19      m      m  9.188
6   107    amar    BE  65.34   19      f      f  8.034
7   108   amita    BE  68.33   23      m      m  8.333
9   110   anmol    BE  78.66   21      f      f  9.366

In [166]:
#drop->drop columns and rows

In [168]:
df

   roll     name class  marks  age gender Gender   CGPA
0   101     anil    TE  56.77   22      m      m  7.177
1   102     amit    TE  59.77   21      m      m  7.477
2   103   aniket    BE  76.88   19      m      m  9.188
3   104  ajinkya    TE  69.66   20      f      f  8.466
4   105     asha    TE  63.28   20      f      f  7.828
5   106     geet    BE  49.55   20      f      f  6.455
6   107     amar    BE  65.34   19      f      f  8.034
7   108    amita    BE  68.33   23      m      m  8.333
8   109     amol    TE  56.75   20      m      m  7.175
9   110    anmol    BE  78.66   21      f      f  9.366

In [169]:
df.drop(4)

   roll     name class  marks  age gender Gender   CGPA
0   101     anil    TE  56.77   22      m      m  7.177
1   102     amit    TE  59.77   21      m      m  7.477
2   103   aniket    BE  76.88   19      m      m  9.188
3   104  ajinkya    TE  69.66   20      f      f  8.466
5   106     geet    BE  49.55   20      f      f  6.455
6   107     amar    BE  65.34   19      f      f  8.034
7   108    amita    BE  68.33   23      m      m  8.333
8   109     amol    TE  56.75   20      m      m  7.175
9   110    anmol    BE  78.66   21      f      f  9.366

In [170]:
df.drop([4,5,6])

   roll     name class  marks  age gender Gender   CGPA
0   101     anil    TE  56.77   22      m      m  7.177
1   102     amit    TE  59.77   21      m      m  7.477
2   103   aniket    BE  76.88   19      m      m  9.188
3   104  ajinkya    TE  69.66   20      f      f  8.466
7   108    amita    BE  68.33   23      m      m  8.333
8   109     amol    TE  56.75   20      m      m  7.175
9   110    anmol    BE  78.66   21      f      f  9.366

In [171]:
#drop name columns

In [175]:
df.drop(columns=['name'])

   roll class  marks  age gender Gender   CGPA
0   101    TE  56.77   22      m      m  7.177
1   102    TE  59.77   21      m      m  7.477
2   103    BE  76.88   19      m      m  9.188
3   104    TE  69.66   20      f      f  8.466
4   105    TE  63.28   20      f      f  7.828
5   106    BE  49.55   20      f      f  6.455
6   107    BE  65.34   19      f      f  8.034
7   108    BE  68.33   23      m      m  8.333
8   109    TE  56.75   20      m      m  7.175
9   110    BE  78.66   21      f      f  9.366

In [176]:
df.drop('name',axis=1)

   roll class  marks  age gender Gender   CGPA
0   101    TE  56.77   22      m      m  7.177
1   102    TE  59.77   21      m      m  7.477
2   103    BE  76.88   19      m      m  9.188
3   104    TE  69.66   20      f      f  8.466
4   105    TE  63.28   20      f      f  7.828
5   106    BE  49.55   20      f      f  6.455
6   107    BE  65.34   19      f      f  8.034
7   108    BE  68.33   23      m      m  8.333
8   109    TE  56.75   20      m      m  7.175
9   110    BE  78.66   21      f      f  9.366

In [177]:
#drop name and class

In [178]:
df.drop(['name','class'],axis=1)

   roll  marks  age gender Gender   CGPA
0   101  56.77   22      m      m  7.177
1   102  59.77   21      m      m  7.477
2   103  76.88   19      m      m  9.188
3   104  69.66   20      f      f  8.466
4   105  63.28   20      f      f  7.828
5   106  49.55   20      f      f  6.455
6   107  65.34   19      f      f  8.034
7   108  68.33   23      m      m  8.333
8   109  56.75   20      m      m  7.175
9   110  78.66   21      f      f  9.366

In [179]:
df.drop(['gender','Gender','CGPA'],axis=1,inplace=True)

In [180]:
df

   roll     name class  marks  age
0   101     anil    TE  56.77   22
1   102     amit    TE  59.77   21
2   103   aniket    BE  76.88   19
3   104  ajinkya    TE  69.66   20
4   105     asha    TE  63.28   20
5   106     geet    BE  49.55   20
6   107     amar    BE  65.34   19
7   108    amita    BE  68.33   23
8   109     amol    TE  56.75   20
9   110    anmol    BE  78.66   21

In [181]:
#create a dataframe
#Columns->roll,gender,cgpa
#roll columns will have the same values as that of in the dataframe

In [199]:
import pandas as pd
new_df = pd.DataFrame({
    'roll': df['roll'],
    'gender': gender,
    'cgpa': df['marks']/10+1.5
})

In [200]:
new_df

   roll gender   cgpa
0   101      m  7.177
1   102      m  7.477
2   103      m  9.188
3   104      f  8.466
4   105      f  7.828
5   106      f  6.455
6   107      f  8.034
7   108      m  8.333
8   109      m  7.175
9   110      f  9.366

In [201]:
# Merge two DataSet

In [202]:
pd.merge(df,new_df)

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      m  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      f  8.466
4   105     asha    TE  63.28   20      f  7.828
5   106     geet    BE  49.55   20      f  6.455
6   107     amar    BE  65.34   19      f  8.034
7   108    amita    BE  68.33   23      m  8.333
8   109     amol    TE  56.75   20      m  7.175
9   110    anmol    BE  78.66   21      f  9.366

In [205]:
#cocat

In [206]:
data=pd.read_csv('student5.csv')

In [207]:
data

   roll     name class  marks  age
0     1   surbhi    TE  67.44   23
1     2    sujay    TE  74.12   22
2     3  subhash    BE  82.44   21
3     4   sachin    TE  59.33   21
4     5  shalini    TE  63.45   20

In [209]:
pd.concat([df,data],ignore_index=True)

    roll     name class  marks  age
0    101     anil    TE  56.77   22
1    102     amit    TE  59.77   21
2    103   aniket    BE  76.88   19
3    104  ajinkya    TE  69.66   20
4    105     asha    TE  63.28   20
5    106     geet    BE  49.55   20
6    107     amar    BE  65.34   19
7    108    amita    BE  68.33   23
8    109     amol    TE  56.75   20
9    110    anmol    BE  78.66   21
10     1   surbhi    TE  67.44   23
11     2    sujay    TE  74.12   22
12     3  subhash    BE  82.44   21
13     4   sachin    TE  59.33   21
14     5  shalini    TE  63.45   20

In [213]:
f=df[(df['marks']>60) & (df['class']=='BE')]

In [214]:
f.to_csv('op.csv',index=False)

In [215]:
f

   roll    name class  marks  age
2   103  aniket    BE  76.88   19
6   107    amar    BE  65.34   19
7   108   amita    BE  68.33   23
9   110   anmol    BE  78.66   21