In [1]:
#Pandas

In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\athra\oracle\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\athra\oracle\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\athra\oracle\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\athra\oracle\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\athra\oracle\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\athra\oracle\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
# 1D Data Structure in pandas

In [6]:
#Pandas Series

In [7]:
#Creating Series

In [8]:
import pandas as pd

In [9]:
s=pd.Series([10,20,30])

In [10]:
s

0    10
1    20
2    30
dtype: int64

In [12]:
series=pd.Series([10,'ABC','Pune'])

In [13]:
series

0      10
1     ABC
2    Pune
dtype: object

In [18]:
#With Index

In [19]:
s=pd.Series([10,20,30],index=['a','b','c'])

In [20]:
s

a    10
b    20
c    30
dtype: int64

In [21]:
s=pd.Series(['Atharv',18,99],index=['Name','Age','Mark'])

In [22]:
s

Name    Atharv
Age         18
Mark        99
dtype: object

In [23]:
# From Dictionary

In [24]:
data={'name':'abc','mark':99,'age':18}

In [25]:
s=pd.Series(data)

In [26]:
s

name    abc
mark     99
age      18
dtype: object

In [27]:
data={'Name':'XYZ','Subject':'Python','Marks':100}

In [28]:
s=pd.Series(data)

In [29]:
s

Name          XYZ
Subject    Python
Marks         100
dtype: object

In [34]:
s=pd.Series(5,index=[1,2,3,4,5])

In [35]:
s

1    5
2    5
3    5
4    5
5    5
dtype: int64

In [36]:
s=pd.Series(index=[1,2,3,4,5,6,7,8,9])

In [37]:
s[:]=5

In [38]:
s

1    5.0
2    5.0
3    5.0
4    5.0
5    5.0
6    5.0
7    5.0
8    5.0
9    5.0
dtype: float64

In [39]:
p=pd.Series([10,20,30],index=['a','b','c'])

In [40]:
p

a    10
b    20
c    30
dtype: int64

In [42]:
p.values

array([10, 20, 30])

In [43]:
p.index

Index(['a', 'b', 'c'], dtype='object')

In [45]:
p.dtype

dtype('int64')

In [47]:
p.shape

(3,)

In [48]:
# Data Mantupulation

In [54]:
series=pd.Series([1,2,3])

In [56]:
print(series* 3)

0    3
1    6
2    9
dtype: int64

In [58]:
# Handling missing value

In [61]:
s=pd.Series([1,None,3])

In [62]:
s

0    1.0
1    NaN
2    3.0
dtype: float64

In [63]:
s.isnull()

0    False
1     True
2    False
dtype: bool

In [65]:
s.dropna()

0    1.0
2    3.0
dtype: float64

In [70]:
s.fillna(0)

0    1.0
1    0.0
2    3.0
dtype: float64

In [71]:
s.isnull()

0    False
1     True
2    False
dtype: bool

In [72]:
# indexing

In [75]:
s=pd.Series([10,20,30],index=['a','b','c'])

In [76]:
s

a    10
b    20
c    30
dtype: int64

In [78]:
s['a']

np.int64(10)

In [79]:
s['c']

np.int64(30)

In [80]:
s['c']=23

In [81]:
s

a    10
b    20
c    23
dtype: int64

In [1]:
'''
Dataframe=>2D data is mutable,
size is mutable
data is heterogenous
'''

'\nDataframe=>2D data is mutable,\nsize is mutable\ndata is heterogenous\n'

In [2]:
import pandas as pd

In [3]:
roll=pd.Series([1,2,3])
name=pd.Series(['ABC','PQR','LMN'])
marks=pd.Series([99,89,87])

In [7]:
df=pd.DataFrame({
    'ID':roll,
    'Name':name,
    'Marks':marks
})

In [8]:
df

   ID Name  Marks
0   1  ABC     99
1   2  PQR     89
2   3  LMN     87

In [9]:
df.shape

(3, 3)

In [11]:
df.ndim

2

In [12]:
df.size

9

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
df['ID']

0    1
1    2
2    3
Name: ID, dtype: int64

In [17]:
df['Name']

0    ABC
1    PQR
2    LMN
Name: Name, dtype: object

In [19]:
df.columns

Index(['ID', 'Name', 'Marks'], dtype='object')

In [21]:
df.columns

Index(['ID', 'Name', 'Marks'], dtype='object')

In [22]:
df.values

array([[1, 'ABC', 99],
       [2, 'PQR', 89],
       [3, 'LMN', 87]], dtype=object)

In [23]:
'''
url-> https://mitu.co.in/dataset

download all dataset starting with student
put them in the sample file folder as ur current working directory
'''

'\nurl-> https://mitu.co.in/dataset\n\ndownload all dataset starting with student\nput them in the sample file folder as ur current working directory\n'

In [24]:
pwd

'C:\\Users\\athra'

In [25]:
df=pd.read_csv("student.csv")

In [26]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [27]:
df=pd.read_csv("student1.csv")

In [28]:
df

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [29]:
col=['roll','Names','percentage','age']

In [31]:
df=pd.read_csv("student1.csv",names=col)

In [32]:
df

       roll Names  percentage  age
1      anil    TE       56.77   22
2      amit    TE       59.77   21
3    aniket    BE       76.88   19
4   ajinkya    TE       69.66   20
5      asha    TE       63.28   20
6    ayesha    BE       49.55   20
7      amar    BE       65.34   19
8     amita    BE       68.33   23
9      amol    TE       56.75   20
10    anmol    BE       78.66   21

In [41]:
df=pd.read_csv("student3.tsv",sep='\t')

In [42]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21