# Section A

In [1]:
'''
Write a function safe_divide(a, b) that divides two numbers and handles ZeroDivisionError and
TypeError separately, printing an appropriate message for each. Use a finally block to print
'Operation attempted.' regardless of the outcome. Test it with valid numbers, division by zero, and a
string input
''';

In [2]:
def safe_divide(a,b):
    try:
        div=a/b
    except ZeroDivisionError :
        print("Can't Divide By Zero")
    except TypeError:
        print("Pass Integer numer as paramter")
    except Exception as e:
        print(e)
    finally:
        print("Run Completed")

In [4]:
safe_divide(12,'String')

Pass Integer numer as paramter
Run Completed

In [5]:
'''
Write a function validate_age(age) that raises a custom exception InvalidAgeError (a class you
define, inheriting from Exception) if age is negative or greater than 120. Catch this exception in a
calling block and print a user-friendly message. Test it with at least 3 different values
''';

In [6]:
class InvalidAge(Exception):
    pass
def validate_age(age):
    if age<0 or age>120:
        raise InvalideAge
    return True

In [7]:
try:
    validate_age(12)
    print("Valide Age")
except Exception as e:
    print("Invalidate Age")

Valide Age

In [9]:
try:
    validate_age(-8)
    print("Valide Age")
except Exception as e:
    print("Invalidate Age")

Invalidate Age

In [10]:
try:
    validate_age(45)
    print("Valide Age")
except Exception as e:
    print("Invalidate Age")

Valide Age

In [11]:
'''
3. Write a program that repeatedly asks the user (use a loop with at least 3 simulated inputs in a list,
e.g. user_inputs = ['10', 'abc', '0', '5']) to enter a number and divide 100 by it. Handle the following in
a single try block using multiple except clauses:
a) ValueError if the input is not a number.
b) ZeroDivisionError if the input is zero.
c) A generic Exception as a catch-all for anything else.
Print the result if successful, otherwise print which error occurred.
''';

In [14]:
user_input=['10','abc','0','5']
for i in user_input:
    print(f"Test Input {i}")
    try:
        number=int(i)
        result=100/number
        print("Successfull")
    except ValueError:
        print(f"ValueError occured")
    except ZeroDivisionError:
        print(f"ZeroDivision Occured")
    except Exception as e:
        print(e)

Test Input 10
Successfull
Test Input abc
ValueError occured
Test Input 0
ZeroDivision Occured
Test Input 5
Successfull

# Section B-> Numpy

In [15]:
'''

 Create a 1D NumPy array of integers from 1 to 20. Perform the following:
a) Reshape it into a 4x5 2D array.
b) Print the sum of each row and each column.
c) Extract all elements greater than 10 using boolean indexing.
d) Replace all even numbers in the array with -1.


''';

In [34]:
import numpy as np

In [42]:
sample_array=np.arange(20)

In [43]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [48]:
reshape=sample_array.reshape((4,5))

In [51]:
reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [49]:
print("Sum of Column is")
np.sum(reshape,axis=0)

Sum of Column is

array([30, 34, 38, 42, 46])

In [50]:
print("Sum of Rows is")
np.sum(reshape,axis=1)

Sum of Rows is

array([10, 35, 60, 85])

In [52]:
filtered_element=reshape[reshape>10]

In [55]:
print(filtered_element)

[11 12 13 14 15 16 17 18 19]

In [56]:
reshape[reshape % 2 == 0] = -1

print("\nArray after replacing even numbers with -1:")
print(sample_array)

Array after replacing even numbers with -1:
[-1  1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19]

In [57]:
'''
 Create two NumPy arrays A and B as shown below and perform:
A = np.array([[1, 2], [3, 4]]) B = np.array([[5, 6], [7, 8]])
a) Element-wise addition, subtraction, and multiplication.
b) Matrix multiplication using np.dot() or the @ operator.
c) Transpose of A.
d) The determinant and inverse of A using np.linalg.
''';

In [58]:
A=np.array([[1,2],[3,4]])

In [59]:
B=np.array([[5,6],[7,8]])

In [62]:
A+B

array([[ 6,  8],
       [10, 12]])

In [63]:
A-B

array([[-4, -4],
       [-4, -4]])

In [64]:
A*B

array([[ 5, 12],
       [21, 32]])

In [65]:
print("Transpose array A")
A.T

Transpose array A

array([[1, 3],
       [2, 4]])

'''
Generate a NumPy array of 15 random integers between 1 and 100 using np.random.randint()
(set a seed of 42 for reproducibility). Then:
a) Find the mean, median, standard deviation, min, and max.
b) Sort the array in descending order.
c) Find the indices of the 3 largest values using np.argsort().
d) Normalize the array so all values lie between 0 and 1.
''';

In [84]:
np.random.seed(45)
arr=np.random.randint(1,100,15)

In [85]:
arr

array([76, 31,  4, 33, 96, 62, 86, 36, 69, 16, 66, 15, 54, 58, 73],
      dtype=int32)

In [87]:
np.sort(arr)

array([ 4, 15, 16, 31, 33, 36, 54, 58, 62, 66, 69, 73, 76, 86, 96],
      dtype=int32)

In [88]:
np.argsort([50,10,30])

array([1, 2, 0])

# Section C — Pandas Basics

In [89]:
'''

7. Create a Pandas DataFrame from the dictionary below and perform the following:
data = { "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"], "Age": [23, 21,
25, 22, 24], "Department": ["AI", "Data Science", "AI", "Web Dev", "Data
Science"], "Score": [88, 92, 79, 95, 67], }
a) Display the first 3 rows and the data types of each column.
b) Add a new column Grade based on Score (>=90 'A', >=75 'B', else 'C').
c) Sort the DataFrame by Score in descending order.
d) Filter rows where Department is 'AI'.

''';

In [90]:
import pandas as pd

In [94]:
data=pd.DataFrame(
    {
        "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
        "Age": [23, 21,25, 22, 24],
        "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
        "Score": [88, 92, 79, 95, 67]
}
)

In [96]:
data

    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
3  Meera   22       Web Dev     95
4  Sahil   24  Data Science     67

In [97]:
data.head(3)

    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79

In [100]:
print("--- First 3 Rows ---")
print(data.head(3))
print("\n--- Column Data Types ---")
print(data.dtypes)

--- First 3 Rows ---
    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79

--- Column Data Types ---
Name          object
Age            int64
Department    object
Score          int64
dtype: object

In [102]:
conditions = [
    data['Score'] >= 90,
    data['Score'] >= 75
]
choices = ['A', 'B']

In [105]:
data['Grade'] = 'C'
data.loc[data['Score'] >= 75, 'Grade'] = 'B'
data.loc[data['Score'] >= 90, 'Grade'] = 'A'

In [106]:
data

    Name  Age    Department  Score Grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C

In [111]:
sort=data.sort_values(by="Score",ascending=False)

In [112]:
print(f"Sorted in Descending")
print(sort)

Sorted in Descending
    Name  Age    Department  Score Grade
3  Meera   22       Web Dev     95     A
1  Priya   21  Data Science     92     A
0  Aarav   23            AI     88     B
2  Karan   25            AI     79     B
4  Sahil   24  Data Science     67     C

In [114]:
ai = data[data['Department'] == 'AI']

print(ai)

    Name  Age Department  Score Grade
0  Aarav   23         AI     88     B
2  Karan   25         AI     79     B

In [115]:
'''
8. Using the same DataFrame from Q7:
a) Group by Department and find the average Score for each.
b) Find the row with the highest Score using idxmax().
c) Rename the column Score to Marks.
d) Drop the Age column and display the resulting DataFrame.
''';

In [119]:
gr=data.groupby('Department')

In [121]:
gr['Score'].mean()

Department
AI              83.5
Data Science    79.5
Web Dev         95.0
Name: Score, dtype: float64

In [122]:
data = data.rename(columns={'Score': 'Marks'})

In [123]:
data

    Name  Age    Department  Marks Grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C

In [126]:
data.drop(columns=['Age'])

    Name    Department  Marks Grade
0  Aarav            AI     88     B
1  Priya  Data Science     92     A
2  Karan            AI     79     B
3  Meera       Web Dev     95     A
4  Sahil  Data Science     67     C

In [ ]:
'''
a) Check the number of missing values in each column using isnull().sum().
b) Fill missing Price values with the column mean.
c) Drop rows where Stock is still missing.
d) Save the cleaned DataFrame to a CSV file named cleaned_products.csv without the index
''';

In [129]:
import pandas as pd

In [131]:
data=pd.DataFrame( { "Product": ["Pen", "Notebook", "Eraser",
"Sharpener", "Ruler"], "Price": [10, np.nan, 5, 8, np.nan], "Stock": [100, 50,
np.nan, 30, 20]})

In [132]:
data

     Product  Price  Stock
0        Pen   10.0  100.0
1   Notebook    NaN   50.0
2     Eraser    5.0    NaN
3  Sharpener    8.0   30.0
4      Ruler    NaN   20.0

In [133]:
data.isnull().sum()

Product    0
Price      2
Stock      1
dtype: int64

In [135]:
data['Price']=data['Price'].fillna(data['Price'].mean())

In [136]:
data

     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
2     Eraser   5.000000    NaN
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0

In [137]:
data = data.dropna(subset=['Stock'])

In [138]:
data

     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0

In [139]:
data.to_csv('cleaned_products.csv',index=False)

In [140]:
data

     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0

In [141]:
'''
10. Read the CSV file created in Q9 (cleaned_products.csv) back into a new DataFrame and:
a) Print its shape and column names.
b) Add a new column Total_Value as Price multiplied by Stock.
c) Use describe() to print summary statistics of the numeric columns.
d) Wrap the file reading step in a try-except block to handle the case where the file does not
exist (FileNotFoundError)
''';

In [142]:
DataFrame=pd.read_csv('cleaned_products.csv')

In [143]:
DataFrame

     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
2  Sharpener   8.000000   30.0
3      Ruler   7.666667   20.0

In [144]:
DataFrame.shape

(4, 3)

In [146]:
DataFrame.columns.tolist()

['Product', 'Price', 'Stock']

In [148]:
DataFrame['Total_Value'] = DataFrame['Price'] * DataFrame['Stock']

In [149]:
DataFrame

     Product      Price  Stock  Total_Value
0        Pen  10.000000  100.0  1000.000000
1   Notebook   7.666667   50.0   383.333333
2  Sharpener   8.000000   30.0   240.000000
3      Ruler   7.666667   20.0   153.333333

In [150]:
DataFrame.describe()

           Price       Stock  Total_Value
count   4.000000    4.000000     4.000000
mean    8.333333   50.000000   444.166667
std     1.122167   35.590261   382.500303
min     7.666667   20.000000   153.333333
25%     7.666667   27.500000   218.333333
50%     7.833333   40.000000   311.666667
75%     8.500000   62.500000   537.500000
max    10.000000  100.000000  1000.000000

In [157]:
try:
    Data=pd.read_csv('cleaned_products.csv')
    print("Successfullt Loaded")
    print(Data.head(3))
except:
    print("File does not exits")

Successfullt Loaded
     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
2  Sharpener   8.000000   30.0